name: Django CI

on:
  push:
    branches:
      - main  # Run tests on every push to the main branch
  pull_request:
    branches:
      - main  # Run tests for pull requests targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    services:
      postgres:
        image: postgres:13  # Specify the PostgreSQL version
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}

    steps:
      # Step 1: Check out the code from the repository
      - uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          make dev-install

      # Step 4: Run Django tests
      - name: Run tests
        env:
            SECRET_KEY: ${{ secrets.SECRET_KEY }}
            DB_NAME: ${{ secrets.DB_NAME }}
            DB_USER: ${{ secrets.DB_USER }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            DB_HOST: localhost
            DB_PORT: 5432
        run: python3 manage.py test apps/user/tests --settings=config.settings.dev
